// AUTO-GENERATED by apply-copy.js — 2026-03-25
// Edit this file to update site content. All pages read from SITE.
// Run: node tools/apply-copy.js --slug psi-automation --template professional-services

export const SITE = {
  // ─── Identity ──────────────────────────────────────────────────────
  name: "PSI Automation",
  slug: "psi-automation",
  logoUrl: '/logo.png',  // TODO: place logo at public/logo.png

  // ─── Contact ───────────────────────────────────────────────────────
  phone: "800-392-3602 (toll-free)",
  email: "sales@psiautomation.com",
  address: "3717 Omni Park Taxiway, Sandpoint, ID 83864 (PO Box 1487)",
  city: "TODO: city",
  state: 'MT',
  zip: "TODO: zip",
  hours: "Call for hours",

  // ─── Brand ─────────────────────────────────────────────────────────
  primaryColor: "TODO: #hex (check their logo or existing site)",
  accentColor: "TODO: #hex (accent/CTA color)",
  heroImage: '/hero.jpg',  // TODO: place hero image at public/hero.jpg

  // ─── Voice & Copy ──────────────────────────────────────────────────
  tagline: "Air Motors Built to Work Hard",
  subheadline: "We manufacture rugged, custom air motors from Montana. Thirty-five years of engineering behind every unit we ship.",
  toneArchetype: "(pending) Local",
  primaryCTA: "Size Your Motor",
  secondaryCTA: "Talk to Engineering",
  footerTagline: "Custom air motors engineered for the job.",
  metaTitle: "PSI Automation | Custom Air Motors | Montana",
  metaDescription: "PSI Automation manufactures rugged, custom air motors in Montana. 35 years of power, durability, and application engineering. Call 800-392-3602.",

  // ─── Stats Bar ─────────────────────────────────────────────────────
  // TODO: fill in real stats for this prospect
  stats: [
    // { value: '15+', label: 'Years in Business' },
    // { value: '500+', label: 'Happy Customers' },
  ],

  // ─── Value Props ───────────────────────────────────────────────────
  valueProps: [
    { title: "Custom-Built for Your Application", description: "Every motor we make fits your specific job. Tell us what you need — we engineer it." },
    { title: "Power That Lasts", description: "Our motors run hard in tough conditions. Built rugged because that's the only way we build." },
    { title: "Real Engineers, Real Answers", description: "Call us. Our application engineers know these motors inside out. We solve problems, not transfer calls." },
  ],

  // ─── About ─────────────────────────────────────────────────────────
  aboutTitle: "Montana-Made Air Motors Since 1989",
  aboutParagraph1: "We started PSI Automation because we saw too many air motors fail when the job got hard. So we built better ones. For thirty-five years, we've designed and manufactured air motors right here in Montana for industries that can't afford downtime.",
  aboutParagraph2: "We're not a catalog company. Every motor we sell, we can customize. Our engineers work directly with you to match the motor to your application.",

  // ─── Services ──────────────────────────────────────────────────────
  // TODO: fill in services for this prospect
  services: [
    // { title: 'Service Name', description: '1-2 sentence description.' },
  ],

  // ─── Reviews & Trust ───────────────────────────────────────────────
  rating: 0,
  reviewCount: 0,
  // TODO: add real testimonials pulled from google-reviews.json
  testimonials: [
    // { name: 'Sarah K.', location: 'Whitefish', text: 'Review text here.', rating: 5 },
  ],

  // ─── Local SEO ─────────────────────────────────────────────────────
  serviceAreas: [/* TODO: add service areas, e.g. 'Whitefish', 'Kalispell' */],

  // ─── Schema.org ────────────────────────────────────────────────────
  schema: {
    category: "professional-services (industrial/manufacturing — B2B)",
    priceRange: '$$',
  },
} as const;
