#!/usr/bin/env node
/**
 * apply-copy.js
 * 
 * Reads a prospect's generated-copy.json and patches it into the
 * appropriate template's SITE config object, creating a ready-to-review
 * customized site in prospects/[slug]/site/.
 * 
 * Usage:
 *   node tools/apply-copy.js --slug flathead-fish-seafood --template restaurant
 * 
 * Input:  prospects/[slug]/generated-copy.json
 * Input:  prospects/[slug]/research.md  (for business info: phone, address, hours)
 * Output: prospects/[slug]/site/  (copied + patched template, ready to run)
 * 
 * Requirements: npm install commander fs-extra
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, cpSync } from 'fs';
import { join } from 'path';

const ROOT = new URL('..', import.meta.url).pathname;
const PROSPECTS_DIR = join(ROOT, 'prospects');
const TEMPLATES_DIR = join(ROOT, 'templates');

// Parse CLI args
function getArg(flag) {
  const i = process.argv.indexOf(flag);
  return i !== -1 ? process.argv[i + 1] : null;
}

const SLUG = getArg('--slug');
const TEMPLATE = getArg('--template') || 'restaurant';

if (!SLUG) {
  console.error('Usage: node tools/apply-copy.js --slug [slug] --template [template-name]');
  process.exit(1);
}

const PROSPECT_DIR = join(PROSPECTS_DIR, SLUG);
const TEMPLATE_DIR = join(TEMPLATES_DIR, TEMPLATE);
const SITE_DIR = join(PROSPECT_DIR, 'site');

// Extract business facts from research.md
function extractFacts(researchMd) {
  const get = (label) => {
    const match = researchMd.match(new RegExp(`\\*\\*${label}:\\*\\*\\s*(.+)`));
    return match ? match[1].trim() : '';
  };
  return {
    name: get('Name'),
    phone: get('Phone'),
    email: get('Email'),
    address: get('Location'),
    hours: (() => {
      const hoursMatch = researchMd.match(/\*\*Hours:\*\*\s*(.+)/);
      return hoursMatch ? hoursMatch[1].trim() : 'Call for hours';
    })(),
  };
}

// Extract extended data needed for siteconfig.ts
function extractSiteConfigData(researchMd) {
  const get = (label) => {
    const match = researchMd.match(new RegExp(`\\*\\*${label}:\\*\\*\\s*(.+)`));
    return match ? match[1].trim() : '';
  };

  // Extract city from address: "123 Main St, Whitefish, MT 59937"
  const cityMatch = researchMd.match(/\*\*Location:\*\*.*?,\s*([A-Za-z\s]+),\s*MT/);
  const city = cityMatch ? cityMatch[1].trim() : '';

  // Extract zip from address
  const zipMatch = researchMd.match(/MT\s*(\d{5})/);
  const zip = zipMatch ? zipMatch[1].trim() : '';

  // Extract brand colors from Brand Elements section (hex only — must start with #)
  const primaryColorMatch = researchMd.match(/\*\*Primary color.*?\*\*:?\s*(#[0-9a-fA-F]{3,6})/);
  const accentColorMatch  = researchMd.match(/\*\*Secondary\/accent color.*?\*\*:?\s*(#[0-9a-fA-F]{3,6})/);

  // Extract service areas (look for serviceAreas list or array in research.md)
  const saMatch = researchMd.match(/\*\*Service Areas?:\*\*\s*\[?([^\n\]]+)/);
  let serviceAreas = [];
  if (saMatch) {
    serviceAreas = saMatch[1].split(',').map(s => s.trim().replace(/["']/g, '')).filter(Boolean);
  }

  // Extract tone archetype (from Voice Brief section)
  const toneMatch = researchMd.match(/\*\*Tone Archetype:\*\*\s*(.+)/);
  const tone = toneMatch ? toneMatch[1].trim().split(' ')[0] + (toneMatch[1].includes('Neighbor') ? ' Neighbor' : toneMatch[1].includes('Expert') ? ' Expert' : toneMatch[1].includes('Pro') ? ' Pro' : ' Local') : 'Polished Pro';

  // Extract rating and review count
  const ratingMatch = researchMd.match(/\*\*Google Rating:\*\*\s*([\d.]+)/);
  const reviewMatch = researchMd.match(/\*\*Google Rating:\*\*[^(]*\(([\d,]+)/);
  const rating = ratingMatch ? parseFloat(ratingMatch[1]) : 0;
  const reviewCount = reviewMatch ? parseInt(reviewMatch[1].replace(/,/g, '')) : 0;

  // Extract schema category
  const schemaCategory = get('Category') || 'Local Business';

  return {
    city,
    zip,
    primaryColor: primaryColorMatch ? primaryColorMatch[1] : 'TODO: #hex (check their logo or existing site)',
    accentColor: accentColorMatch ? accentColorMatch[1] : 'TODO: #hex (accent/CTA color)',
    serviceAreas,
    toneArchetype: tone,
    rating,
    reviewCount,
    schemaCategory,
  };
}

// Write siteconfig.ts to prospects/[slug]/site/src/config/
function writeSiteConfig(copy, facts, extended) {
  const configDir = join(SITE_DIR, 'src', 'config');
  if (!existsSync(configDir)) mkdirSync(configDir, { recursive: true });

  const serviceAreasStr = extended.serviceAreas.length
    ? extended.serviceAreas.map(s => `'${s}'`).join(', ')
    : `/* TODO: add service areas, e.g. 'Whitefish', 'Kalispell' */`;

  const config = `// AUTO-GENERATED by apply-copy.js — ${new Date().toISOString().split('T')[0]}
// Edit this file to update site content. All pages read from SITE.
// Run: node tools/apply-copy.js --slug ${SLUG} --template ${TEMPLATE}

export const SITE = {
  // ─── Identity ──────────────────────────────────────────────────────
  name: ${JSON.stringify(facts.name || `TODO: business name`)},
  slug: ${JSON.stringify(SLUG)},
  logoUrl: '/logo.png',  // TODO: place logo at public/logo.png

  // ─── Contact ───────────────────────────────────────────────────────
  phone: ${JSON.stringify(facts.phone || `TODO: phone`)},
  email: ${JSON.stringify(facts.email || ``)},
  address: ${JSON.stringify(facts.address || `TODO: address`)},
  city: ${JSON.stringify(extended.city || `TODO: city`)},
  state: 'MT',
  zip: ${JSON.stringify(extended.zip || `TODO: zip`)},
  hours: ${JSON.stringify(facts.hours || 'Call for hours')},

  // ─── Brand ─────────────────────────────────────────────────────────
  primaryColor: ${JSON.stringify(extended.primaryColor)},
  accentColor: ${JSON.stringify(extended.accentColor)},
  heroImage: '/hero.jpg',  // TODO: place hero image at public/hero.jpg

  // ─── Voice & Copy ──────────────────────────────────────────────────
  tagline: ${JSON.stringify(copy.heroHeadline || `TODO: hero headline`)},
  subheadline: ${JSON.stringify(copy.heroSubheadline || `TODO: hero subheadline`)},
  toneArchetype: ${JSON.stringify(extended.toneArchetype)},
  primaryCTA: ${JSON.stringify(copy.primaryCTA || 'Get a Free Quote')},
  secondaryCTA: ${JSON.stringify(copy.secondaryCTA || 'Call Now')},
  footerTagline: ${JSON.stringify(copy.footerTagline || ``)},
  metaTitle: ${JSON.stringify(copy.titleTag || `${facts.name || 'Business'} | ${extended.city || 'Montana'}`)},
  metaDescription: ${JSON.stringify(copy.metaDescription || ``)},

  // ─── Stats Bar ─────────────────────────────────────────────────────
  // TODO: fill in real stats for this prospect
  stats: [
    // { value: '15+', label: 'Years in Business' },
    // { value: '500+', label: 'Happy Customers' },
  ],

  // ─── Value Props ───────────────────────────────────────────────────
  valueProps: [
${copy.valueProps ? copy.valueProps.map(vp => `    { title: ${JSON.stringify(vp.title)}, description: ${JSON.stringify(vp.description)} },`).join('\n') : `    // TODO: add value props`}
  ],

  // ─── About ─────────────────────────────────────────────────────────
  aboutTitle: ${JSON.stringify(copy.aboutTitle || `TODO: about title`)},
  aboutParagraph1: ${JSON.stringify(copy.aboutParagraph1 || ``)},
  aboutParagraph2: ${JSON.stringify(copy.aboutParagraph2 || ``)},

  // ─── Services ──────────────────────────────────────────────────────
  // TODO: fill in services for this prospect
  services: [
    // { title: 'Service Name', description: '1-2 sentence description.' },
  ],

  // ─── Reviews & Trust ───────────────────────────────────────────────
  rating: ${extended.rating || 0},
  reviewCount: ${extended.reviewCount || 0},
  // TODO: add real testimonials pulled from google-reviews.json
  testimonials: [
    // { name: 'Sarah K.', location: 'Whitefish', text: 'Review text here.', rating: 5 },
  ],

  // ─── Local SEO ─────────────────────────────────────────────────────
  serviceAreas: [${serviceAreasStr}],

  // ─── Schema.org ────────────────────────────────────────────────────
  schema: {
    category: ${JSON.stringify(extended.schemaCategory)},
    priceRange: '$$',
  },
} as const;
`;

  writeFileSync(join(configDir, 'siteconfig.ts'), config);
  console.log(`✅ siteconfig.ts written to prospects/${SLUG}/site/src/config/siteconfig.ts`);
}

function run() {
  // Validate inputs
  if (!existsSync(PROSPECT_DIR)) {
    console.error(`No prospect folder found: prospects/${SLUG}/`);
    process.exit(1);
  }
  if (!existsSync(TEMPLATE_DIR)) {
    console.error(`No template found: templates/${TEMPLATE}/`);
    console.error(`Available templates: outdoor-adventure, restaurant, lodging, professional-services, retail-boutique, auto-services`);
    process.exit(1);
  }

  const copyPath = join(PROSPECT_DIR, 'generated-copy.json');
  const researchPath = join(PROSPECT_DIR, 'research.md');

  if (!existsSync(copyPath)) {
    console.error(`No generated-copy.json found. Run first: node tools/generate-copy.js --slug ${SLUG}`);
    process.exit(1);
  }
  if (!existsSync(researchPath)) {
    console.error(`No research.md found in prospects/${SLUG}/`);
    process.exit(1);
  }

  const copy = JSON.parse(readFileSync(copyPath, 'utf8'));
  const research = readFileSync(researchPath, 'utf8');
  const facts = extractFacts(research);
  const extended = extractSiteConfigData(research);

  console.log(`\n📁 Copying template (${TEMPLATE}) → prospects/${SLUG}/site/`);

  // Copy template to site dir (overwrite if exists)
  if (existsSync(SITE_DIR)) {
    console.log('   Site dir exists — overwriting...');
  }
  cpSync(TEMPLATE_DIR, SITE_DIR, { recursive: true });

  console.log('✅ Template copied');
  console.log('📝 Patching SITE config with generated copy...');

  // Read page.tsx from the copied site
  const pagePath = join(SITE_DIR, 'src', 'app', 'page.tsx');
  if (!existsSync(pagePath)) {
    console.error(`No page.tsx found at ${pagePath}`);
    process.exit(1);
  }

  let pageContent = readFileSync(pagePath, 'utf8');

  // Apply patches by finding the SITE object and replacing key values
  // We replace line-by-line string matches within the SITE config block
  const patches = {
    // Hero
    heroH1: copy.heroHeadline,
    heroSub: copy.heroSubheadline,
    heroCTA1: copy.primaryCTA,
    heroCTA2: copy.secondaryCTA,

    // About
    aboutTitle: copy.aboutTitle,
    aboutP1: copy.aboutParagraph1,
    aboutP2: copy.aboutParagraph2,

    // Footer
    footerTagline: copy.footerTagline,

    // Business facts
    phone: facts.phone,
    email: facts.email,
    address: facts.address,
  };

  // Replace string values in the SITE config object
  for (const [key, value] of Object.entries(patches)) {
    if (!value) continue;
    // Match: key: 'old value', and replace the old value with the new one
    const regex = new RegExp(`(\\b${key}:\\s*['"\`])([^'"\`]*)(['"\`])`, 'g');
    pageContent = pageContent.replace(regex, `$1${value.replace(/'/g, "\\'")}$3`);
  }

  // Apply value props (more complex — replace the valueProps array)
  if (copy.valueProps && copy.valueProps.length === 3) {
    const vpBlock = `valueProps: [
    {
      icon: '✓',
      title: '${copy.valueProps[0].title}',
      desc: '${copy.valueProps[0].description.replace(/'/g, "\\'")}',
    },
    {
      icon: '✓',
      title: '${copy.valueProps[1].title}',
      desc: '${copy.valueProps[1].description.replace(/'/g, "\\'")}',
    },
    {
      icon: '✓',
      title: '${copy.valueProps[2].title}',
      desc: '${copy.valueProps[2].description.replace(/'/g, "\\'")}',
    },
  ],`;

    // Find and replace the valueProps block
    const vpRegex = /valueProps:\s*\[[\s\S]*?\],/;
    if (vpRegex.test(pageContent)) {
      pageContent = pageContent.replace(vpRegex, vpBlock);
    }
  }

  writeFileSync(pagePath, pageContent);

  // Write siteconfig.ts — the per-prospect config file for the clone architecture
  writeSiteConfig(copy, facts, extended);

  // Also update layout.tsx metadata
  const layoutPath = join(SITE_DIR, 'src', 'app', 'layout.tsx');
  if (existsSync(layoutPath)) {
    let layout = readFileSync(layoutPath, 'utf8');
    if (facts.name) {
      layout = layout.replace(/(name:\s*['"])([^'"]*)(["'])/, `$1${facts.name}$3`);
    }
    if (copy.metaDescription) {
      layout = layout.replace(/(description:\s*['"])([^'"]*)(["'])/, `$1${copy.metaDescription.replace(/'/g, "\\'")}$3`);
    }
    if (copy.titleTag) {
      layout = layout.replace(/title:\s*`[^`]*`/, `title: \`${copy.titleTag}\``);
    }
    writeFileSync(layoutPath, layout);
  }

  console.log('✅ Copy applied to site\n');
  console.log('📋 What was patched:');
  console.log(`   Hero: "${copy.heroHeadline}"`);
  console.log(`   About: "${copy.aboutTitle}"`);
  console.log(`   CTA: "${copy.primaryCTA}"`);
  console.log(`   Phone: ${facts.phone}`);
  console.log('');
  console.log('🔍 Next steps:');
  console.log(`   1. cd prospects/${SLUG}/site && npm install && npm run dev`);
  console.log('   2. Review at localhost:3000 — adjust copy/colors as needed');
  console.log(`   3. node tools/deploy-demo.js --slug ${SLUG}`);
}

run();
